---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 發表內容
    url: "/index.html"
  - title: 適用於NetApp文件的風格
    url: "/style.html"
  - title: AsciDoc參考資料
    url: "/asciidoc_syntax.html"
  - title: AI產生內容的原則
    url: "/ai-policy.html"
  - title: 法律聲明
    url: "/legal-notices.html"
